version: '3'
services:
  gitolite:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-gitolite
      args:
        - ADMIN_PUB_KEY
    ports:
      - "62666:22"
    restart: always
    volumes:
      - gitdata:/home/git
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
      args:
        - "SERVER_NAME_VALUE=${SERVER_NAME_VALUE}"
    restart: always
    ports:
      - "43448:80"
    volumes:
      - gitdata:/git
volumes:
  gitdata:
