FROM alpine:3.13

ARG ADMIN_PUB_KEY

RUN apk upgrade -U && \
    apk --update add --no-cache \
    git \
    perl \
    openssh && \
    rm -rf /var/cache/apk/* && \
    adduser -D git && \
    passwd -u git && \
    /usr/bin/ssh-keygen -A && \
    echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config && \
    echo 'PermitRootLogin no' >> /etc/ssh/sshd_config

COPY ./docker/entrypoint /

USER git
ENV USER=git
EXPOSE 22

WORKDIR /tmp

RUN git clone https://github.com/sitaramc/gitolite && \
    echo "${ADMIN_PUB_KEY}" > /tmp/admin.pub

WORKDIR /home/git

USER root
ENTRYPOINT ["/entrypoint"]
