FROM nginx:1.20.0-alpine

RUN apk upgrade -U && \
    apk --update add --no-cache \
    git-gitweb \
    fcgiwrap \
    perl-cgi && \
    chown -R nginx:nginx /usr/share/gitweb

WORKDIR /usr/share/gitweb

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/site.conf /etc/nginx/conf.d/default.conf
COPY ./docker/gitweb.conf /etc/gitweb.conf

ARG SERVER_NAME_VALUE

# TODO: Set instance name using ENV variables
RUN sed -i "s/Untitled/${SERVER_NAME_VALUE}/" /usr/share/gitweb/gitweb.cgi

CMD /usr/bin/fcgiwrap -s unix:/run/fcgiwrap/fw.sock& sleep 1 && /bin/chown nginx:nginx /run/fcgiwrap/fw.sock && nginx -g "daemon off;"
